### ISSUE TITLE
"Sometimes" validation

### ISSUE THREAD

**Issue by eduardostuart** [ragunathjawahar/android-saripaar#143]
Hi,

Is possible to handle "sometimes" validation? Example:

Rule:
Password: Not required, but if "not empty" should have at least 6 chars.

**Comment by ragunathjawahar** [comment]
Yeah, there's an upcoming `@OptionalOrValid` annotation.

**Comment by eduardostuart** [comment]
Awesome! Thanks @ragunathjawahar

**Comment by eduardostuart** [comment]
Can I suggest something?

Maybe.. a param is better than another annotation.

```
@ValidPassword(min = 6,  scheme = Password.Scheme.NUMERIC,  sometimes = 1 )
``` 
Where: 
"sometimes" check if password is not empty. If empty, check if is a valid password.

**Comment by lepipele** [comment]
For what is worth - I see that lots issues opened here are somewhat related to issue I now participate in:

https://github.com/ragunathjawahar/android-saripaar/issues/127

Basically, what we all are asking for is ability to _change_ rules based on certain set of conditions. Now @ragunathjawahar I STRONGLY advise you against going with MORE attributes, because in a nutshell what you are doing is creating programing language within Java. 

And there is simply no need for that. You already have Java as programming language. Attributes are TERRIBLE when it comes to flexibility for simple reason - you use them to NOTATE something. So you shouldn't use them in case where it's like - Oh, it COULD be this... but it also COULD be that.

To conclude - let's create a way to easily change rules programmatically and I'm sure everything else will fall in line.

**Comment by JehandadK** [comment]
I believe creating a rule is easy programmatically, could you perhaps share some examples of what you mean.

P.S. New user of saripaar. Love It!

**Comment by ragunathjawahar** [comment]
@lepipele I'm against attributes as well. Follow #102 for updates.
