### ISSUE TITLE
How to unhide errorPopups (Edittext)

### ISSUE THREAD

**Issue by rinav** [ragunathjawahar/android-saripaar#35]
Hi,

How can I unhide the Validation failure pop ups shown during  failure after validation succeeds ?

```
@Override
public void onValidationSucceeded() {
        Toast.makeText(MatchBotApplication.getAppContext(), "Yay! we got it right!", Toast.LENGTH_SHORT).show();

    // Some code to unhide all the popups shown in the failure callback
    }

@Override
public void onValidationFailed(View failedView, Rule<?> failedRule) {

    String message = failedRule.getFailureMessage();

    if (failedView instanceof EditText) {
        failedView.requestFocus();
        ((EditText) failedView).setError(message);
    } else {
    Toast.makeText(MatchBotApplication.getAppContext(), message, Toast.LENGTH_SHORT).show();
    }
```

**Comment by ericn37** [comment]
Any update of this @ragunathjawahar ? :D

**Comment by rjoncontract** [comment]
@ericn37 Isn't [`DefaultViewValidatedAction`](https://github.com/ragunathjawahar/android-saripaar/blob/master/saripaar/src/main/java/com/mobsandgeeks/saripaar/DefaultViewValidatedAction.java) taking care of this already? You can also supply your own `ViewValidatedAction` to the `Validator.setViewValidatedAction(viewValidatedAction)` method.

**Comment by awidiyadew** [comment]
Thanks @rjoncontract you give me a clue..
in my case DefaultViewValidatedAction is not solving my problem because I set Error to `TextInputLayout`. So I make a custom `ViewValidatedAction` which is implement `Validator.ViewValidatedAction`.

Here is my gist [https://gist.github.com/awidiyadew/2e7723b8a7349ce4ec749f6dc9b693f9](url)
Thanks
